apiVersion: v2
name: vault
description: Helm chart for deploying HashiCorp Vault on Minikube
type: application
version: 0.1.0
appVersion: "1.15.2"
keywords:
  - vault
  - hashicorp
  - secrets
home: https://www.vaultproject.io/
sources:
  - https://github.com/lineirv-hue/vault_helm
maintainers:
  - name: lineirv-hue
