apiVersion: v1
kind: ConfigMap
metadata:
  # Name must match vault.server.volumes[].configMap.name in values.yaml
  name: vault-minikube-logrotate
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  vault: |
    {{ .Values.vaultLogs.dir }}/{{ .Values.vaultLogs.file }} {
      size {{ .Values.vaultLogrotate.rotate.size }}
      {{- if .Values.vaultLogrotate.rotate.copytruncate }}
      copytruncate
      {{- end }}
      rotate {{ .Values.vaultLogrotate.rotate.keep }}
      {{- if .Values.vaultLogrotate.rotate.compress }}
      compress
      {{- end }}
      missingok
      notifempty
    }
