apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  vault.hcl: |
    ui = {{ .Values.vault.ui }}

    listener "tcp" {
      address     = "{{ .Values.vault.listener.address }}:{{ .Values.vault.listener.port }}"
      tls_disable = {{ .Values.vault.listener.tlsDisable }}
    }

    storage "file" {
      path = "{{ .Values.vault.storage.path }}"
    }

    disable_mlock = {{ .Values.vault.disableMlock }}
    log_level = "{{ .Values.vault.logLevel }}"
